output_total_dir: output/
experiment: main
model_name: model
checkpoint: null
save_log: True

tracking:
  type: swanlab
  workspace: null
  project: WillMindS.AI
  experiment_name: pretrain
  description: null
  config: null
  logdir: null
  ####################################################
  # mode:
  # #### for swanlab: "cloud"、"local"、"disabled"
  # #### for wandb: 'online', 'offline', 'disabled'
  ####################################################
  mode: cloud  

train:
  load_training_arguments: True
  learning_rate: 5e-4
  num_train_epochs: 1
  seed: 42
  per_device_train_batch_size: 32
  gradient_accumulation_steps: 8
  logging_steps: 100
  save_strategy: epoch  # no / epoch / steps / best
  save_steps: 100
  save_safetensors: False
  warmup_steps: 0
  max_grad_norm: 1.0
  bf16: True
  local_rank: -1
  dataloader_num_workers: 0
  device: cuda:0
  dtype: bfloat16

model:
  dim: 512
  n_layers: 8
  n_heads: 8
  n_kv_heads: 2
  vocab_size: 6400
  hidden_dim: null
  multiple_of: 64
  norm_eps: 1e-5
  max_seq_len: 8192
  rope_theta: 1e6
  dropout: 0.0
  flash_attn: True
  ####################################################
  # Here are the specific configurations of MOE
  # When use_moe is false, the following is invalid
  ####################################################
  use_moe: False
  ####################################################
  num_experts_per_tok: 2
  n_routed_experts: 4
  n_shared_experts: True
  scoring_func: softmax
  aux_loss_alpha: 0.1
  seq_aux: True
  norm_topk_prob: True